config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'likes/create'
  # get 'comments/new'
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # user ||= User.new # guest user (not logged in)
    can :read, :all
    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    can :manage, Like, author_id: user.id

    return unless user.admin?

    can :manage, :all

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, counter_cache: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, counter_cache: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :author, class_name: 'User', counter_cache: true

  validates :title, presence: true
  validates :title, length: { maximum: 250 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy, foreign_key: 'author_id'
  has_many :posts, dependent: :destroy, foreign_key: 'author_id'
  has_many :likes, dependent: :destroy, foreign_key: 'author_id'

  validates :name, presence: true

  ROLES = [:admin].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def admin?
    role == 'admin'
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostController < ActionController::Base
      # before_action :check_basic_auth
      # skip_before_action :verify_authenticity_token

  #     private

  #     def check_basic_auth
  #       unless request.authorization.present?
  #         head :unauthorized
  #         return
  #       end

  #       authenticate_with_http_basic do |email, password|
  #         user = User.find_by(email: email.downcase)

  #         if user && user.authenticate(password)
  #           @current_user = user
  #         else
  #           head :unauthorized
  #         end
  #       end
  #     end

  #     def current_user
  #       @current_user
  #     end
  #   end
  # end

      def index
        @posts = Post.all.order
        render json: {success: true, data: { comments: @posts  }}
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :photo, :bio, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :bio, :password, :photo, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]

    if @comment.save
      flash[:notice] = 'Comment created successfuly!'
      redirect_to user_post_path(current_user, @comment.post)
    else
      flash.now[:alert] = 'Failed to create Comment!!'
      render :new
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    post = comment.post
    comment.destroy!

    flash[:alert] = 'Comment Deleted'
    redirect_back fallback_location: [post]
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @like = @user.likes.new(post_id: @post.id, author_id: @user.id)

    if @like.save
      flash[:notice] = 'Like created successfully!!'
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:alert] = 'Failed to create Like!!'
    end
  end

  def like_params
    params.require(:likes).permit(:user_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def create
    @user = current_user
    @post = @user.posts.create(post_params)
    if @post.save
      flash[:notice] = 'Post created successfully!'
      redirect_to user_posts_path(@user)
    else
      flash.now[:alert] = 'Failed to create Post!!'
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.destroy
    flash[:alert] = 'Deleted post'
    redirect_to user_posts_path
  end

  def post_params
    params.permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<% flash.each do |type, msg| %>
  <div class="flash align-items-center text-secondary bg-warning border-0" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
      <div class="toast-body">
      <%= msg %>
      </div>
      <a href="#" class="btn-close btn-close-white me-2 m-auto" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
  </div>
<% end %>

<%= form_with( model: @comment, url: {action: "create"}, method: :post) do |form| %>
  <div>
    <%= render partial: 'shared/textarea', locals: { form: form, label: "comment" } %>
  </div>

  <div class="submit d-flex">
    <%= form.submit "submit", class: "mt-1 btn btn-outline-primary btn-lg" %>
  </div>
<% end %>

app/views/layouts/_navbar.erb
<nav class="navbar fixed-top navbar-light bg-light">
  <section class="container">
    <h1 class="navbar-brand">
      <%= link_to "TechivaBloggers", users_path %>
    </h1>
    <article class="d-flex">
      <div class="m-2">
        <%= link_to "About", user_path(current_user) %>
      </div>
      <div class="m-2">
        <%= link_to "Posts", user_posts_path(current_user) %>
      </div>
    </article>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechivaBloggers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('blog.png') %>
    <%= stylesheet_link_tag 'application.bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <section class="container pb-4">
      <% if user_signed_in? %>
        <%= render 'layouts/navbar' %>
      <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit User', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </p>
      <%= yield %>
    <section>
  </body>
</html>

app/views/posts/index.html.erb
<Section class="d-flex flex-column">
  <% flash.each do |type, msg| %>
    <div class="flash align-items-center text-secondary bg-warning border-0" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="d-flex">
        <div class="toast-body">
        <%= msg %>
        </div>
      <a href="#" class="btn-close btn-close-white me-2 m-auto" data-dismiss="alert" aria-label="close">&times;</a>
      </div>
    </div>
  <% end %>

  <%= render partial: 'shared/user', locals: { user: @user } %>

  <% if @posts.any? == false %>
    <p>There are no posts yet !!!</p>
  <% end %>

  <section class="w-75 align-self-center">
    <h1>All posts</h1>
    <% @posts.each do |post| %>
      <%= render partial: 'shared/post', locals: { post: post, length: 40 } %>
      <%= render partial: 'shared/comment', collection: post.recent_comments, locals: { post: @post, user: @user } %>
      <% if can? :destroy, post %>
          <%= button_to 'Delete post', user_post_path(@user, post), method: :delete, data: { confirm: "Are you sure you want to delete #{post.title}?" }, class: 'delete btn btn-danger text-end mb-2' %>
      <% end %>
    <% end %>

    <div class="d-flex  m-1 w-100">
      <%= link_to "Add Post", new_user_post_path(@user), class: 'm-auto btn btn-primary text-center w-25'%>
    </div>
  </section>
</section>

app/views/posts/new.html.erb
<% flash.each do |type, msg| %>
  <div class="flash align-items-center text-secondary bg-warning border-0" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
      <div class="toast-body">
      <%= msg %>
      </div>
      <a href="#" class="btn-close btn-close-white me-2 m-auto" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
  </div>
<% end %>


<%= form_with( model: @user, url: {action: "create"}, method: :post) do |form| %>
  <div class="input">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= render partial: 'shared/textarea', locals: {form: form, label: "Post" } %>
  </div>

  <div class="w-100 d-flex">
    <%= form.submit "submit", class: "mt-1 btn btn-outline-primary btn-lg" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<% flash.each do |type, msg| %>
  <div class="flash align-items-center text-secondary bg-warning border-0 rounded" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
      <div class="toast-body">
      <%= msg %>
      </div>
      <a href="#" class="btn-close btn-close-white me-2 m-auto" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
  </div>
<% end %>

<h1>Posts by <%= @user.name %></h1>
<div class="posts">
<%= render partial: 'shared/post', locals: { post: @post, length: 1/0.0 } %>
<div class="border rounded pt-3 pb-5 px-3">
<%= "There are no comments" if @comments.empty? %>
  <% @comments.each do |comment| %>
    <div class="container row">
      <div class="col-md-10 d-flex">
        <div class="">
          <%= comment.author.name %>:
        </div>
        &nbsp
        <div id="text-justify">
          <%= comment.text %>
        </div>
      </div>
      <span class="col-md-2">  
        <% if can? :destroy, comment %>
          <%= button_to 'Delete Comment', user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" }, class: 'm-1 btn btn-danger text-end justify-self-end' %>
        <% end %>
      </span>
    </div>
  <% end %>
</div>
<div class="d-flex my-2">
    <div class="m-1">
        <%= link_to "Add Comment", new_user_post_comment_path(@user, @post), class: "btn btn-primary btn-lg" %>
    </div>

    <div class="m-1"> 
      <%= button_to "Add Like", user_post_likes_path(@user, @post), class: "btn btn-primary btn-lg"%>
    </div>
  </div>
</div>

app/views/shared/_comment.html.erb
<p class="border rounded pt-3 pb-5 px-3">
  <span>
    <%= comment.author.name %> : 
  </span>
  <span>
    <%= truncate( comment.text, length: 20) %>
  </span>
</p>

app/views/shared/_post.html.erb
<%= link_to user_post_path(@user.id, post.id) do %>  
  <div class="border rounded pt-3 pb-5 px-3">
    <div>
      <h3> <%= post.title %> </h3>
      <p class="pt-2"><%= truncate(post.text, length: length) %></p>
    </div>
    <div>
      <span>Comments: <%= post.comments_count || 0 %>,</span>
      <span>Likes: <%= post.likes_count || 0 %></span>
    </div>
  </div>
  <br>
<% end %>

app/views/shared/_textarea.html.erb
<div class="input">
  <%= form.label :text, label %><br>
  <%= form.text_area  :text, class: "form-control" %>
</div>

app/views/shared/_user.html.erb
<%= link_to user_path(user.id) do %>
  <article class="user-container d-flex m-auto justify-content-center">
    <img src="<%= user.photo %>" alt="<%= user.name %>'s avatar" width="200" height="172.44">
    <div class="user-card d-lg-flex align-items-center border rounded py-4 px-5 ms-5">
      <h4 class="ps-1"><%= user.name %><sub>(<%= user.role %>)</sub></h4>
      <p class="ps-5 mx-5 mt-5">Number of posts: <%= user.posts.count%></p>
    </div>
  </article>
  <br>
<% end %>  

app/views/users/index.html.erb
<%= render partial: 'shared/user', collection: @users %>

app/views/users/show.html.erb
<%= render partial: 'shared/user', locals: { user: @user } %>

<section class="container w-75" id="bio-container">
  <article class="border pb-5 pt-3 px-3" >
    <h3 class="pb-2">Bio</h3>
    <p><%= @user.bio %></p>
  </article>
  <h3 class="py-2">Posts</h3>
  <%= render partial: 'shared/post', collection: @posts, locals: { length: 40} %>
  <%= link_to "See all posts", user_posts_path(@user.id), class: "btn btn-primary my-5" %>
</section>